apiVersion: apps/v1
kind: Deployment
metadata:
  name: vproapp
  labels:
    app: vproapp
spec:
  replicas: 1

  selector:
    matchLabels:
      app: vproapp

  template:
    metadata:
      labels:
        app: vproapp
        
    spec:
      containers:
        - name: vproapp
          image: 996818459618.dkr.ecr.us-east-1.amazonaws.com/vprofile-app:fe4d374c60d01724387ca1db7c4a321da3936c5d
          imagePullPolicy: Always

          ports:
            - containerPort: 8080
              name: vproapp-port

      initContainers:
        - name: init-db
          image: busybox
          command:
            [
              "sh",
              "-c",
              "until nslookup vprodb.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for mydb; sleep 2; done",
            ]
        - name: init-rabbitmq
          image: busybox
          command:
            [
              "sh",
              "-c",
              "until nslookup vpromq01.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for myservice; sleep 2; done",
            ]
